variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "region" {}
variable "vpc_id" {}
variable "cidr_block" {}
variable "pbl_subnet_ids" {}
variable "pvt_subnet_ids" {}
variable "cce_subnet_ids" {}
variable "public_key" {}
variable "kms_key_id" {}
variable "additional_ips" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "cluster_flavor" {}
variable "load_balancer_enabled" {}
variable "load_balancer_bandwidth" {}
variable "metrics_server_version" {}
variable "auto_scaler_profile" {}
variable "root_disk_size" {}
variable "root_disk_type" {}
variable "root_disk_iops" {}
variable "root_disk_throughput" {}
variable "main_instance_types" {}
variable "main_os" {}
variable "main_max_pods" {}
variable "main_scaling_config" {}
variable "extra_nodes_deploy" {}
variable "data_disk_size" {}
variable "data_disk_type" {}
variable "data_disk_iops" {}
variable "data_disk_throughput" {}
variable "extra_instance_types" {}
variable "extra_os" {}
variable "extra_max_pods" {}
variable "extra_scaling_config" {}
variable "sfs_turbo_storages" {}
